server:
  port: 8082

spring:
  application:
    name: employer-service
  datasource:
    url: jdbc:mysql://localhost:3306/employer_service
    username: root
    password: revathi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: common-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"